# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Spotlight' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Spotlight

  target 'SpotlightTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'SpotlightUITests' do
    # Pods for testing
  end
 
  pod 'SwiftGen', '~> 6.0'
  pod 'Alamofire', '~> 5.5'
  pod 'SDWebImage', '~> 5.0'
  pod 'SwiftLint'
end
